version: '3.8'

services:
  site:
    build: .
    container_name: astro-site
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - astro-site-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - site
    networks:
      - astro-site-network

networks:
  astro-site-network:
    driver: bridge
